# Generated by Django 4.2.10 on 2024-02-11 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_alter_article_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_body', models.CharField(max_length=150)),
                ('craeted', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(default=uuid.UUID('2cc543d7-d718-4ae7-8153-8a8bd8ebb38b'), max_length=100, primary_key=True, serialize=False, unique=True)),
                ('muallif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Comments', to=settings.AUTH_USER_MODEL)),
                ('parent_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='articles.article')),
            ],
        ),
    ]
