# Generated by Django 4.2.10 on 2024-02-11 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default=uuid.UUID('dd871558-3ade-410a-8d1e-ce18e6a37519'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
